default[:localwiki][:database][:host] = "127.0.0.1"
default[:localwiki][:database][:user] = "localwiki"
default[:localwiki][:database][:db_name] = "localwiki"
default[:localwiki][:superuser][:username] = "admin"
default[:localwiki][:superuser][:email] = "admin@example.com"
default[:localwiki][:repository][:url] = "git://github.com/localwiki/localwiki.git"
default[:localwiki][:repository][:reference] = "master"
default[:localwiki][:repository][:action] = "checkout"
