default[:localwiki][:database][:host] = "127.0.0.1"
default[:localwiki][:database][:user] = "localwiki"
default[:localwiki][:database][:db_name] = "localwiki"
default[:localwiki][:superuser][:username] = "admin"
default[:localwiki][:superuser][:email] = "admin@example.com"
